; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	C:\Users\216-12\Desktop\2018-11-30\3_macro\macro.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?gVar@@3HA					; gVar
_BSS	SEGMENT
?gVar@@3HA DD	01H DUP (?)				; gVar
_BSS	ENDS
PUBLIC	_main
PUBLIC	??_C@_0CC@LDHDOGNG@a?5?$DN?5?$CFd?0?5gVar?5?$DN?5?$CFd?0?5SUM?$CIb?0c?$CJ?5?$DN?5?$CFd@ ; `string'
EXTRN	__imp__printf:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_0CC@LDHDOGNG@a?5?$DN?5?$CFd?0?5gVar?5?$DN?5?$CFd?0?5SUM?$CIb?0c?$CJ?5?$DN?5?$CFd@
CONST	SEGMENT
??_C@_0CC@LDHDOGNG@a?5?$DN?5?$CFd?0?5gVar?5?$DN?5?$CFd?0?5SUM?$CIb?0c?$CJ?5?$DN?5?$CFd@ DB 'a'
	DB	' = %d, gVar = %d, SUM(b,c) = %d', 0aH, 00H	; `string'
CONST	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\216-12\desktop\2018-11-30\3_macro\macro.cpp
;	COMDAT _main
_TEXT	SEGMENT
_c$ = -32						; size = 4
_b$ = -20						; size = 4
_a$ = -8						; size = 4
_main	PROC						; COMDAT

; 15   : int main() {

	push	ebp
	mov	ebp, esp
	sub	esp, 228				; 000000e4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-228]
	mov	ecx, 57					; 00000039H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 16   : 	int a, b = 10;

	mov	DWORD PTR _b$[ebp], 10			; 0000000aH

; 17   : 	const int c = 30;

	mov	DWORD PTR _c$[ebp], 30			; 0000001eH

; 18   : 	a = b;

	mov	eax, DWORD PTR _b$[ebp]
	mov	DWORD PTR _a$[ebp], eax

; 19   : 	a = c;

	mov	DWORD PTR _a$[ebp], 30			; 0000001eH

; 20   : 	a = MAX;

	mov	DWORD PTR _a$[ebp], 1000		; 000003e8H

; 21   : 	
; 22   : 	printf("a = %d, gVar = %d, SUM(b,c) = %d\n", a, gVar, SUM(b,c));

	mov	eax, DWORD PTR _b$[ebp]
	add	eax, 30					; 0000001eH
	mov	esi, esp
	push	eax
	mov	ecx, DWORD PTR ?gVar@@3HA		; gVar
	push	ecx
	mov	edx, DWORD PTR _a$[ebp]
	push	edx
	push	OFFSET ??_C@_0CC@LDHDOGNG@a?5?$DN?5?$CFd?0?5gVar?5?$DN?5?$CFd?0?5SUM?$CIb?0c?$CJ?5?$DN?5?$CFd@
	call	DWORD PTR __imp__printf
	add	esp, 16					; 00000010H
	cmp	esi, esp
	call	__RTC_CheckEsp

; 23   : 
; 24   : 	return 0;

	xor	eax, eax

; 25   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 228				; 000000e4H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
